### ISSUE TITLE
More Basic Customizablity

### ISSUE THREAD

**Issue by TheJoshue** [RefracDevelopment/SimpleStaffChat2#9]
Hello,

I respect work on this plugin and time put in,
but can you please make this menu editable
this happens when you type either `/staffchat` or any alias to it (i think by default there is one called `/sc`)

This shows on both spigot and bungee side of the plugin

can you please make this editable, like config option to have
```yml
messages:
  staffchat-output: "default" #if this is exactly "default", the output of this command will always be like you define it - hardcoded message; however if we change this to anything else, that else will be displayed!
  <...>
```

Thank you so much, also make sure to do this for spigot & bungee side of the plugin too!
